//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurora_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsInOrder
    {
        public int id { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> countProduct { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
