//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurora_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.CreateProducts = new HashSet<CreateProduct>();
            this.ItemsInOrders = new HashSet<ItemsInOrder>();
        }
    
        public int id { get; set; }
        public string orderNumber { get; set; }
        public Nullable<int> recipientId { get; set; }
        public string paymentMethod { get; set; }
        public decimal price { get; set; }
        public string orderStatus { get; set; }
        public string creationDate { get; set; }
        public Nullable<int> managerId { get; set; }
        public byte[] contractSkan { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreateProduct> CreateProducts { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsInOrder> ItemsInOrders { get; set; }
    }
}
