//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFModernVerticalMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateProduct
    {
        public int id { get; set; }
        public int productId { get; set; }
        public int countProduct { get; set; }
        public Nullable<int> forOrder { get; set; }
        public string status { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
